export type LocalStationRecord = {
  id: string;
  legalName: string;
  displayName: string;
  cnpj: string;
  address: string | null;
  brand: string | null;
  aliases: string[];
  status: "cadastro_ativo" | "operacao_nao_verificada" | "encerramento_indicado";
  sourceNote: string;
};

export const AGUAS_LINDAS_STATIONS_UPDATED_AT = "2026-09-30";

export const AGUAS_LINDAS_STATIONS_SOURCE =
  "Cadastro empresarial público de empresas ativas no CNAE 4731-8/00, cruzado com referências locais e buscas públicas. O cadastro não garante que a unidade esteja aberta hoje.";

export const AGUAS_LINDAS_STATIONS: LocalStationRecord[] = [
  {
    id: "mizuno-kay",
    legalName: "Mizuno Kay & Cia LTDA",
    displayName: "Mizuno Kay & Cia",
    cnpj: "00.375.386/0002-05",
    address: "Rodovia BR-070, km 25, Gleba 02-B, Zona Rural",
    brand: null,
    aliases: ["Posto Mizuno Kay", "Mizuno Kay"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo; endereço rural também aparece em documento público do Estado de Goiás.",
  },
  {
    id: "aguas-lindas-posto-servicos",
    legalName: "Águas Lindas Posto Serviços LTDA",
    displayName: "Posto Águas Lindas",
    cnpj: "01.268.557/0001-70",
    address: "Rodovia BR-070, km 28, Parque da Barragem, Setor 08",
    brand: null,
    aliases: ["Aguas Lindas Posto Serviços", "Posto Aguas Lindas"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo.",
  },
  {
    id: "auto-posto-jardim-brasilia",
    legalName: "Auto Posto Jardim Brasilia LTDA",
    displayName: "Auto Posto Jardim Brasília",
    cnpj: "02.316.635/0001-28",
    address: "Avenida JK, Jardim Brasília / Jardim Santa Lúcia",
    brand: null,
    aliases: ["Auto Posto Jardim Brasilia"],
    status: "encerramento_indicado",
    sourceNote: "Cadastro empresarial ativo na fonte cadastral consultada; uma ficha pública de mapas indica encerramento, portanto a situação operacional deve ser confirmada.",
  },
  {
    id: "real-auto-posto",
    legalName: "Real Auto Posto e Serviços LTDA",
    displayName: "Real Auto Posto",
    cnpj: "02.907.378/0001-07",
    address: "Quadra 46, Conjunto B, nº 05, Jardim Querência",
    brand: null,
    aliases: ["Real Auto Posto e Serviços", "Real Auto Posto"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo.",
  },
  {
    id: "aj-combustiveis",
    legalName: "A J Comércio de Combustíveis e Derivados LTDA",
    displayName: "A J Comércio de Combustíveis",
    cnpj: "05.159.610/0001-56",
    address: null,
    brand: null,
    aliases: ["A J Comércio de Combustíveis", "AJ Combustíveis"],
    status: "operacao_nao_verificada",
    sourceNote: "Cadastro empresarial ativo; endereço físico não consolidado nas fontes públicas consultadas nesta coleta.",
  },
  {
    id: "df-180",
    legalName: "Auto Posto DF 180 LTDA",
    displayName: "Auto Posto DF 180",
    cnpj: "07.347.238/0002-18",
    address: "Quadra 08, s/n, Jardim Querência",
    brand: "Ipiranga",
    aliases: ["Auto Posto DF 180", "Posto DF 180"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência local pública.",
  },
  {
    id: "juraci-junior",
    legalName: "Auto Posto Juraci Junior LTDA",
    displayName: "Auto Posto Juraci Junior",
    cnpj: "09.373.967/0001-93",
    address: "Quadra 06, s/n, Setor Jardim Querência",
    brand: null,
    aliases: ["Auto Posto JJR", "Auto Posto Juraci Junior"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência local pública.",
  },
  {
    id: "jj-junior",
    legalName: "Auto Posto J.J Junior LTDA",
    displayName: "Auto Posto J.J Junior",
    cnpj: "10.515.562/0001-21",
    address: "Avenida JK, Jardim Brasília",
    brand: null,
    aliases: ["Auto Posto J.J", "Auto Posto J J Junior"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo; ficha pública de mapas atualizada para a cidade.",
  },
  {
    id: "ponteio",
    legalName: "Auto Posto Ponteio LTDA",
    displayName: "Posto Ponteio",
    cnpj: "11.030.816/0001-84",
    address: "Quadra 02, s/n, Vivendas Paraíso / Parque da Barragem",
    brand: null,
    aliases: ["Auto Posto Ponteio", "Posto Ponteio"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referências públicas de localização.",
  },
  {
    id: "guaira",
    legalName: "Auto Posto Guaira LTDA",
    displayName: "Posto Guaíra",
    cnpj: "12.560.575/0001-48",
    address: "Rodovia BR-070, Quadra 28, lotes 16/17",
    brand: "Ipiranga",
    aliases: ["Auto Posto Guaira", "Posto Guaira"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência recente de preços da ANP.",
  },
  {
    id: "aguas-lindas-combustiveis",
    legalName: "Águas Lindas Combustíveis LTDA",
    displayName: "Águas Lindas Combustíveis",
    cnpj: "13.902.675/0001-78",
    address: "Quadra 07, s/n, Lote 33, Camping Clube",
    brand: null,
    aliases: ["Aguas Lindas Combustiveis"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência recente de preços da ANP.",
  },
  {
    id: "rp",
    legalName: "Auto Posto RP LTDA",
    displayName: "Posto RP",
    cnpj: "14.700.372/0001-35",
    address: "Avenida Brasília, Setor 10 / Parque da Barragem",
    brand: null,
    aliases: ["Auto Posto RP", "Posto RP"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e ficha pública de mapas.",
  },
  {
    id: "morais",
    legalName: "Auto Posto Morais LTDA",
    displayName: "Auto Posto Morais",
    cnpj: "17.571.211/0001-87",
    address: "Quadra 25, s/n, Lote 12/13, Parque Águas Bonitas I",
    brand: null,
    aliases: ["Auto Posto Morais", "Auto Posto Águas Bonitas"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência pública de posto em Águas Bonitas.",
  },
  {
    id: "gb",
    legalName: "Auto Posto GB LTDA",
    displayName: "Auto Posto GB",
    cnpj: "18.689.286/0001-20",
    address: "Avenida 1, Parque da Barragem",
    brand: null,
    aliases: ["Auto Posto GB"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência local pública.",
  },
  {
    id: "hospital",
    legalName: "Auto Posto do Hospital LTDA",
    displayName: "Auto Posto do Hospital",
    cnpj: "19.090.135/0001-13",
    address: "Quadra 29, Conjunto A, Lote 05A, Parque da Barragem, Setor 08",
    brand: null,
    aliases: ["Auto Posto do Hospital"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência local pública.",
  },
  {
    id: "f1",
    legalName: "Posto F1 LTDA",
    displayName: "Posto F1 / Fórmula 1",
    cnpj: "20.244.886/0001-26",
    address: "Jardim Brasília",
    brand: null,
    aliases: ["Posto F1", "Posto Formula 1", "Fórmula 1"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência de preços da ANP.",
  },
  {
    id: "barragem-v",
    legalName: "Posto Barragem V LTDA",
    displayName: "Posto Barragem V / Premium",
    cnpj: "21.570.661/0001-22",
    address: "Quadra 09, Jardim Querência",
    brand: null,
    aliases: ["Posto Barragem V", "Posto Premium"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo; fontes públicas usam também a denominação Posto Premium.",
  },
  {
    id: "furacao",
    legalName: "Mariana Comércio de Combustível LTDA",
    displayName: "Furacão Auto Posto",
    cnpj: "26.631.982/0001-03",
    address: "Quadra 55, s/n, Parque Águas Bonitas I",
    brand: null,
    aliases: ["Mariana Comércio de Combustível", "Furacao Auto Posto"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência local pública.",
  },
  {
    id: "premium-aguas-lindas",
    legalName: "Posto Premium de Águas Lindas LTDA",
    displayName: "Posto Premium de Águas Lindas",
    cnpj: "29.753.244/0001-27",
    address: "Quadra 09, lotes 01/04, Jardim Querência",
    brand: null,
    aliases: ["Posto Premium de Aguas Lindas", "Posto Formula 1"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo; referências públicas usam nomes comerciais sobrepostos.",
  },
  {
    id: "setor-08",
    legalName: "Posto Setor 08 LTDA",
    displayName: "Posto Setor 08",
    cnpj: "31.405.435/0001-40",
    address: "Quadra 34, Conjunto A, Parque da Barragem, Setor 08",
    brand: null,
    aliases: ["Posto Setor 08"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência local pública.",
  },
  {
    id: "aguas-bonitas-empreendimentos",
    legalName: "Águas Bonitas Empreendimentos Imobiliários LTDA",
    displayName: "Auto Posto Águas Bonitas",
    cnpj: "31.599.286/0001-05",
    address: "Quadra 25, s/n, Parque Águas Bonitas I",
    brand: null,
    aliases: ["Auto Posto Aguas Bonitas"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo; nome empresarial difere do nome comercial público.",
  },
  {
    id: "posto-combustivel-aguas-lindas",
    legalName: "Posto de Combustível Águas Lindas LTDA",
    displayName: "Posto de Combustível Águas Lindas",
    cnpj: "34.742.673/0001-39",
    address: "Rodovia BR-070, Quadra 0002B, s/n, Chácaras Coimbra",
    brand: null,
    aliases: ["Posto de Combustivel Aguas Lindas"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência pública municipal de endereço.",
  },
  {
    id: "nossa-senhora-santana",
    legalName: "Posto Nossa Senhora de Sant'ana LTDA",
    displayName: "Posto Nossa Senhora de Santana",
    cnpj: "40.833.628/0001-92",
    address: null,
    brand: null,
    aliases: ["Posto Nossa Senhora de Sant'ana", "Posto Nossa Senhora de Santana"],
    status: "operacao_nao_verificada",
    sourceNote: "Cadastro empresarial ativo; endereço físico não consolidado nesta coleta.",
  },
  {
    id: "prime",
    legalName: "Posto Prime LTDA",
    displayName: "Posto Prime",
    cnpj: "46.080.060/0001-62",
    address: null,
    brand: null,
    aliases: ["Posto Prime", "Posto Premium"],
    status: "operacao_nao_verificada",
    sourceNote: "Cadastro empresarial ativo; endereço físico não consolidado nesta coleta.",
  },
  {
    id: "campeao",
    legalName: "Posto Campeão de Águas Lindas LTDA",
    displayName: "Posto Campeão de Águas Lindas",
    cnpj: "46.355.254/0001-23",
    address: "Quadra 52, Lote 1344, Chácaras Quedas do Descoberto",
    brand: null,
    aliases: ["Posto Campeao de Aguas Lindas", "Posto Premium"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência pública de mapas/endereço.",
  },
  {
    id: "setor-04",
    legalName: "Posto Setor 04 LTDA",
    displayName: "Posto Setor 04 / Brasil",
    cnpj: "50.437.240/0001-26",
    address: null,
    brand: null,
    aliases: ["Posto Setor 04", "Posto Brasil"],
    status: "operacao_nao_verificada",
    sourceNote: "Cadastro empresarial ativo; endereço físico não consolidado nesta coleta.",
  },
  {
    id: "sao-jose",
    legalName: "Posto São José LTDA",
    displayName: "Posto São José",
    cnpj: "52.505.400/0001-52",
    address: "Quadra 97, Lote 83/83A, Jardim Brasília 2",
    brand: null,
    aliases: ["Posto Sao Jose"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e ficha pública de mapas.",
  },
  {
    id: "forquilha-ii",
    legalName: "Auto Posto Forquilha II LTDA",
    displayName: "Auto Posto Forquilha II",
    cnpj: "54.438.110/0001-69",
    address: null,
    brand: null,
    aliases: ["Auto Posto Forquilha II", "Forquilha"],
    status: "operacao_nao_verificada",
    sourceNote: "Cadastro empresarial ativo; endereço físico não consolidado nesta coleta.",
  },
  {
    id: "zm",
    legalName: "ZM Combustíveis LTDA",
    displayName: "ZM Combustíveis",
    cnpj: "55.846.090/0001-28",
    address: "Recreio das Águas Lindas",
    brand: null,
    aliases: ["ZM Combustiveis"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e ficha pública de mapas.",
  },
  {
    id: "pitstop-2",
    legalName: "Posto Pitstop 2 LTDA",
    displayName: "Posto Pitstop 2",
    cnpj: "60.979.745/0001-76",
    address: "Quadra 5, lotes 18-21, Jardim Querência",
    brand: null,
    aliases: ["Posto Pitstop 2", "Posto Pitstop"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo e referência pública de endereço.",
  },
  {
    id: "coimbra",
    legalName: "Auto Posto Coimbra LTDA",
    displayName: "Auto Posto Coimbra",
    cnpj: "66.684.330/0001-51",
    address: "Chácaras Coimbra",
    brand: null,
    aliases: ["Auto Posto Coimbra"],
    status: "cadastro_ativo",
    sourceNote: "Cadastro empresarial ativo desde 08/05/2026.",
  },
];

export function searchAguasLindasStations(query: string) {
  const normalized = query.trim().toLocaleLowerCase("pt-BR");
  if (!normalized || normalized === "postos" || normalized === "combustíveis" || normalized === "combustiveis" || normalized === "postos de combustíveis" || normalized === "postos de combustivel") {
    return AGUAS_LINDAS_STATIONS;
  }
  return AGUAS_LINDAS_STATIONS.filter(station =>
    [station.displayName, station.legalName, station.cnpj, station.address ?? "", station.brand ?? "", ...station.aliases]
      .join(" ")
      .toLocaleLowerCase("pt-BR")
      .includes(normalized),
  );
}

export function stationMapsSearchUrl(station: LocalStationRecord) {
  const query = [station.displayName, station.address, "Águas Lindas de Goiás", "GO"].filter(Boolean).join(", ");
  return "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(query);
}
