export type CoverageShareCardInput = { city: string; state: string; corridor: string; authorizedStations: number; sourceDate: string; url: string };

const escapeXml = (value: string) => value.replace(/[<>&'"']/g, char => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[char] ?? char);

export function buildCoverageShareCardSvg(input: CoverageShareCardInput) {
  const city = escapeXml(input.city); const corridor = escapeXml(input.corridor); const sourceDate = escapeXml(input.sourceDate);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0a1015"/><stop offset="1" stop-color="#17272a"/></linearGradient><pattern id="grid" width="42" height="42" patternUnits="userSpaceOnUse"><path d="M42 0H0V42" fill="none" stroke="#55e6ff" stroke-opacity=".13"/></pattern></defs><rect width="1200" height="630" fill="url(#g)"/><rect width="1200" height="630" fill="url(#grid)"/><circle cx="1030" cy="130" r="170" fill="#c7ff3c" fill-opacity=".12"/><circle cx="1000" cy="500" r="230" fill="#3de3ff" fill-opacity=".08"/><text x="74" y="96" fill="#c7ff3c" font-family="Arial, sans-serif" font-size="26" font-weight="700" letter-spacing="5">TRAJETO · COBERTURA PÚBLICA</text><text x="74" y="208" fill="#fff" font-family="Arial, sans-serif" font-size="82" font-weight="700">${city}</text><text x="78" y="258" fill="#b6c5c9" font-family="Arial, sans-serif" font-size="30">${escapeXml(input.state)} · ${corridor}</text><rect x="74" y="330" width="414" height="170" rx="28" fill="#c7ff3c"/><text x="106" y="382" fill="#22310c" font-family="Arial, sans-serif" font-size="22" font-weight="700" letter-spacing="2">CADASTRO OFICIAL DISPONÍVEL</text><text x="106" y="462" fill="#0b1014" font-family="Arial, sans-serif" font-size="88" font-weight="700">${input.authorizedStations}</text><text x="256" y="456" fill="#22310c" font-family="Arial, sans-serif" font-size="25">revendedores<br/>autorizados</text><text x="74" y="568" fill="#9ab0b6" font-family="Arial, sans-serif" font-size="20">Fonte: catálogo ANP armazenado · atualização: ${sourceDate}</text><text x="1125" y="568" text-anchor="end" fill="#c7ff3c" font-family="Arial, sans-serif" font-size="20">trajeto</text></svg>`;
}

export const coverageShareCardUrl = (input: CoverageShareCardInput) => `data:image/svg+xml;charset=utf-8,${encodeURIComponent(buildCoverageShareCardSvg(input))}`;
export const coverageShareCardFilename = (city: string) => `trajeto-cobertura-${city.toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-")}.svg`;
