export type LocalPlaceCategory = "alimentacao" | "compras" | "servicos" | "referencia";

export type LocalPlace = {
  id: string;
  name: string;
  detail: string;
  address: string;
  category: LocalPlaceCategory;
  sourceLabel: string;
  sourceUrl?: string;
  mapQuery: string;
  phone?: string;
  tags?: string[];
};

export const LOCAL_PLACES_UPDATED_AT = "30/09/2026";

const SHOPPING_SOURCE = "https://www.aguaslindasshopping.com.br/loja.asp";
const SHOPPING_ADDRESS = "Águas Lindas Shopping, Alameda Santa Luzia, Mansões Centro-Oeste, Águas Lindas de Goiás, GO";
const SHOPPING_SOURCE_LABEL = "Águas Lindas Shopping · diretório online";

export const LOCAL_PLACES: LocalPlace[] = [
  {
    id: "giraffas-shopping",
    name: "Giraffas · Águas Lindas Shopping",
    detail: "Alimentação · Praça de alimentação",
    address: "Av. Santa Luzia, s/n, Loja 038, Águas Lindas de Goiás, GO, 72915-705",
    category: "alimentacao",
    sourceLabel: "Consulta local",
    mapQuery: "Giraffas Shopping Águas Lindas, Águas Lindas de Goiás, GO",
    phone: "4000-1515",
    tags: ["restaurante", "fast-food", "shopping"],
  },
  {
    id: "burger-house-shell",
    name: "Burger House Shell",
    detail: "Hambúrguer · BR-070",
    address: "BR-070, 285, Mansões Centro-Oeste, Águas Lindas de Goiás, GO, 72910-000",
    category: "alimentacao",
    sourceLabel: "Consulta local",
    mapQuery: "Burger House Shell, Águas Lindas de Goiás, GO",
    phone: "(61) 99866-9544",
    tags: ["hamburgueria", "lanche", "24h"],
  },
  {
    id: "tapiocaria-familia",
    name: "Tapiocaria Família",
    detail: "Café da manhã · lanches · delivery",
    address: "Jardim América, Águas Lindas de Goiás, GO",
    category: "alimentacao",
    sourceLabel: "Consulta local",
    mapQuery: "Tapiocaria Família, Águas Lindas de Goiás, GO",
    phone: "(61) 98223-2811",
    tags: ["tapioca", "café", "delivery"],
  },
  {
    id: "spoleto-shopping",
    name: "Spoleto · Águas Lindas Shopping",
    detail: "Alimentação · comida italiana",
    address: SHOPPING_ADDRESS,
    category: "alimentacao",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Spoleto Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["restaurante", "shopping"],
  },
  {
    id: "bobs-shopping",
    name: "Bob's · Águas Lindas Shopping",
    detail: "Alimentação · lanches",
    address: SHOPPING_ADDRESS,
    category: "alimentacao",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Bob's Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["fast-food", "shopping"],
  },
  {
    id: "burger-king-shopping",
    name: "Burger King · Águas Lindas Shopping",
    detail: "Alimentação · fast-food",
    address: SHOPPING_ADDRESS,
    category: "alimentacao",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Burger King Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["hambúrguer", "fast-food", "shopping"],
  },
  {
    id: "giraffas-quiosque",
    name: "Giraffas · Quiosque Shopping",
    detail: "Alimentação · quiosque",
    address: "BR-070, Mansões Centro-Oeste, Águas Lindas de Goiás, GO",
    category: "alimentacao",
    sourceLabel: "Consulta local",
    mapQuery: "Giraffas Quiosque Shopping Águas Lindas, Águas Lindas de Goiás, GO",
    phone: "4000-1515",
    tags: ["fast-food", "shopping"],
  },
  {
    id: "agittus",
    name: "Agittus",
    detail: "Calçados · Águas Lindas Shopping",
    address: "Av. Marginal, lojas 09/10, Mansões Centro-Oeste, Águas Lindas de Goiás, GO, 72915-705",
    category: "compras",
    sourceLabel: "Consulta local",
    mapQuery: "Agittus, Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    phone: "(61) 99606-4963",
    tags: ["calçados", "shopping"],
  },
  {
    id: "tim-shopping",
    name: "TIM · Águas Lindas Shopping",
    detail: "Telefonia celular",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "TIM Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["celular", "telefonia"],
  },
  {
    id: "claro-shopping",
    name: "Claro · Águas Lindas Shopping",
    detail: "Telefonia celular",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Claro Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["celular", "telefonia"],
  },
  {
    id: "neo-cell",
    name: "Neo Cell",
    detail: "Eletrônicos e acessórios",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Neo Cell Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["eletrônicos", "celular"],
  },
  {
    id: "realme-shopping",
    name: "Realme · Águas Lindas Shopping",
    detail: "Eletrônicos · telefonia",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Realme Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["celular", "eletrônicos"],
  },
  {
    id: "lojas-americanas-shopping",
    name: "Lojas Americanas · Águas Lindas Shopping",
    detail: "Loja de departamentos",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Lojas Americanas Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["departamento", "shopping"],
  },
  {
    id: "riachuelo-shopping",
    name: "Riachuelo · Águas Lindas Shopping",
    detail: "Vestuário · loja de departamentos",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Riachuelo Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["roupas", "shopping"],
  },
  {
    id: "polo-seven",
    name: "Polo Seven",
    detail: "Vestuário masculino",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Polo Seven Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["roupas", "masculino"],
  },
  {
    id: "constance-shopping",
    name: "Constance · Águas Lindas Shopping",
    detail: "Calçados e acessórios",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Constance Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["calçados", "acessórios"],
  },
  {
    id: "bretas-shopping",
    name: "Bretas Supermercados · Shopping",
    detail: "Supermercado",
    address: SHOPPING_ADDRESS,
    category: "compras",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Bretas Supermercados Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["mercado", "compras"],
  },
  {
    id: "lotérica-shopping",
    name: "Lotérica · Águas Lindas Shopping",
    detail: "Serviços financeiros",
    address: SHOPPING_ADDRESS,
    category: "servicos",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Lotérica Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    phone: "(61) 3613-7574",
    tags: ["lotérica", "pagamentos"],
  },
  {
    id: "caixa-shopping",
    name: "Caixa Econômica Federal · Shopping",
    detail: "Banco e atendimento",
    address: SHOPPING_ADDRESS,
    category: "servicos",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Caixa Econômica Federal Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["banco", "caixa", "atm"],
  },
  {
    id: "oftalmed-shopping",
    name: "Oftalmed Hospital da Visão",
    detail: "Saúde · diagnóstico e visão",
    address: SHOPPING_ADDRESS,
    category: "servicos",
    sourceLabel: SHOPPING_SOURCE_LABEL,
    sourceUrl: SHOPPING_SOURCE,
    mapQuery: "Oftalmed Hospital da Visão Águas Lindas Shopping, Águas Lindas de Goiás, GO",
    tags: ["saúde", "visão"],
  },
  {
    id: "drogaria-exclusiva",
    name: "Drogaria Exclusiva",
    detail: "Farmácia · delivery e retirada",
    address: "Quadra 14, Lote 01, Lojas 1 e 2, Jardim Águas Lindas II, Águas Lindas de Goiás - GO, 72927-662",
    category: "servicos",
    sourceLabel: "Consulta local",
    mapQuery: "Drogaria Exclusiva, Águas Lindas de Goiás, GO",
    phone: "(61) 99405-8441",
    tags: ["farmácia", "delivery"],
  },
  {
    id: "maria-fifi-store",
    name: "Maria Fifi Store",
    detail: "Roupas femininas",
    address: "Quadra 30, Lote 26, Jardim Brasília, Águas Lindas de Goiás - GO, 72915-111",
    category: "compras",
    sourceLabel: "Consulta local",
    mapQuery: "Maria Fifi Store, Águas Lindas de Goiás, GO",
    tags: ["roupas", "moda feminina"],
  },
  {
    id: "tudo-18",
    name: "TUDO 18",
    detail: "Loja de roupas · Parque da Barragem",
    address: "Parque da Barragem, Setor 8, Águas Lindas de Goiás - GO, 72910-052",
    category: "compras",
    sourceLabel: "Consulta local",
    mapQuery: "TUDO 18, Parque da Barragem, Águas Lindas de Goiás, GO",
    phone: "(61) 98250-1582",
    tags: ["roupas", "moda"],
  },
  {
    id: "lojas-bijuterias",
    name: "Lojas das Bijuterias",
    detail: "Bijuterias e acessórios",
    address: "Av. JK, Condomínio Privê Mansões Águas Lindas, Águas Lindas de Goiás - GO",
    category: "compras",
    sourceLabel: "Consulta local",
    mapQuery: "Lojas das Bijuterias, Águas Lindas de Goiás, GO",
    tags: ["bijuterias", "acessórios"],
  },
  {
    id: "locmaq-brasil",
    name: "Locmaq do Brasil",
    detail: "Locação de ferramentas e equipamentos",
    address: "Quadra 1B, Lote 58, Loja 04, Jardim da Barragem III, Águas Lindas de Goiás - GO, 72920-530",
    category: "servicos",
    sourceLabel: "Consulta local",
    mapQuery: "Locmaq do Brasil, Águas Lindas de Goiás, GO",
    phone: "(61) 3613-9768",
    tags: ["ferramentas", "equipamentos", "locação"],
  },
  {
    id: "banco-do-brasil-4590",
    name: "Banco do Brasil · Agência 4590",
    detail: "Banco · Jardim Brasília",
    address: "Av. JK, s/n, Jardim Brasília, Águas Lindas de Goiás - GO, 72915-006",
    category: "servicos",
    sourceLabel: "Consulta local",
    mapQuery: "Banco do Brasil Agência 4590, Águas Lindas de Goiás, GO",
    phone: "4003-3001",
    tags: ["banco", "atm"],
  },
];

export function searchLocalPlaces(query = "", category?: LocalPlaceCategory) {
  const normalized = query.trim().toLocaleLowerCase("pt-BR");
  return LOCAL_PLACES.filter(place => {
    if (category && place.category !== category) return false;
    if (!normalized) return true;
    return [
      place.name,
      place.detail,
      place.address,
      place.category,
      ...(place.tags ?? []),
    ].join(" ").toLocaleLowerCase("pt-BR").includes(normalized);
  });
}
