import { expect, test } from "@playwright/test";
test.use({ serviceWorkers: "block" });
for (const width of [320, 1280]) test(`map controls: categories, local layer and public place actions at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 320 ? 568 : 800 });
  await page.addInitScript(() => {
    Object.defineProperty(navigator, "share", { configurable: true, value: undefined });
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async (value: string) => { (window as any).__copiedPlace = value; } } });
  });
  await page.route("https://tile.openstreetmap.org/**", route => route.fulfill({ contentType: "image/png", body: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64") }));
  await page.goto("mapa", { waitUntil: "domcontentloaded" });
  const map = page.locator('section[aria-label="Mapa da cidade"]');
  const surface = map.getByRole("region", { name: "Mapa de destinos", exact: true });
  await expect(surface).toBeVisible();
  if (width === 320) expect(await surface.locator('img[src*="tile.openstreetmap.org"]').count()).toBeLessThanOrEqual(30);
  await surface.focus();
  await surface.press("ArrowRight");
  await surface.press("+");
  await expect(map.getByRole("button", { name: "Diminuir zoom", exact: true })).toBeEnabled();
  await map.getByRole("button", { name: "Recentrar mapa", exact: true }).click();
  await map.getByRole("button", { name: "Escolher destino no mapa" }).click();
  const popup = page.locator('[data-slot="popover-content"]');
  await popup.getByRole("button", { name: "Saúde", exact: true }).click();
  const first = popup.getByRole("option").first();
  const selectedName = (await first.locator(".font-bold").textContent())!;
  await first.click();
  await expect(map.locator("p").filter({ hasText: selectedName }).first()).toBeVisible();
  await map.getByRole("button", { name: "Compartilhar", exact: true }).click();
  await expect(map.getByText("Link do lugar copiado para enviar.")).toBeVisible();
  expect(await page.evaluate(() => (window as any).__copiedPlace)).toContain("destino=");
  expect(await page.evaluate(() => (window as any).__copiedPlace)).not.toContain("origem=");
  await map.getByRole("button", { name: "Medir a partir daqui" }).click();
  await map.getByRole("button", { name: "Escolher destino no mapa" }).click();
  await popup.getByRole("button", { name: "Saúde", exact: true }).click();
  await popup.getByRole("option").last().click();
  await expect(map.getByText(/em linha reta/)).toBeVisible();
  await map.getByRole("button", { name: "Encerrar medição" }).click();
  await map.getByRole("button", { name: "Abrir mapa local offline" }).click();
  await expect(map.getByRole("img", { name: /Mapa offline vetorial/ })).toBeVisible();
  await map.getByRole("button", { name: "Usar mapa claro" }).click();
  await expect(map.getByRole("button", { name: "Usar mapa escuro" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
  if (process.env.MAP_QA_SCREENSHOT) await map.screenshot({ path: `/tmp/trajeto-map-${width}.png` });
  await map.getByRole("button", { name: /Ampliar grupo de/ }).first().click();
  await expect(map.getByRole("button", { name: "Diminuir zoom", exact: true })).toBeEnabled();
  await map.getByRole("button", { name: "Voltar ao mapa de ruas" }).click();
  await expect(map.getByRole("button", { name: "Escolher destino no mapa" })).toBeVisible();
});
