import { ArrowRight, CalendarDays, Download, Fuel, Receipt } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { fuelLogEvent, listFuelLog } from "@/lib/fuelLog";
import { listMobilityExpenses, mobilityExpenseEvent } from "@/lib/mobilityExpenses";
import { appUrl } from "@/lib/appUrl";

function money(value:number){return value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function inCurrentMonth(date:string, now=new Date()){const d=new Date(date);return Number.isFinite(d.getTime())&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()}
export function summarizeCurrentMobilityMonth(now=new Date()){const fuel=listFuelLog().filter(x=>inCurrentMonth(x.date,now));const expenses=listMobilityExpenses().filter(x=>inCurrentMonth(x.date,now));const fuelCost=fuel.reduce((s,x)=>s+x.totalCost,0);const extraCost=expenses.reduce((s,x)=>s+x.amount,0);return {fuelEntries:fuel.length,fuelCost,extraEntries:expenses.length,extraCost,total:fuelCost+extraCost,entries:fuel.length+expenses.length}}
export function buildCurrentMobilityCsv(now=new Date()){const fuel=listFuelLog().filter(x=>inCurrentMonth(x.date,now));const expenses=listMobilityExpenses().filter(x=>inCurrentMonth(x.date,now));const rows=[["Data","Tipo","Categoria","Litros","Valor (R$)","Observação"],...fuel.map(x=>[new Date(x.date).toLocaleDateString("pt-BR"),"Abastecimento","Combustível",x.liters.toFixed(2),x.totalCost.toFixed(2),x.note||""]),...expenses.map(x=>[new Date(x.date).toLocaleDateString("pt-BR"),"Despesa",x.category,"",x.amount.toFixed(2),x.note||""])];return rows.map(row=>row.map(value=>'"'+String(value).replace(/"/g,'""')+'"').join(";")).join("\n")}
export default function MobilityDashboardCard(){const[stamp,setStamp]=useState(0);useEffect(()=>{const r=()=>setStamp(x=>x+1);window.addEventListener(fuelLogEvent,r);window.addEventListener(mobilityExpenseEvent,r);return()=>{window.removeEventListener(fuelLogEvent,r);window.removeEventListener(mobilityExpenseEvent,r)}},[]);const summary=useMemo(()=>summarizeCurrentMobilityMonth(),[stamp]);const month=new Date().toLocaleDateString("pt-BR",{month:"long",year:"numeric"});const download=()=>{const blob=new Blob([buildCurrentMobilityCsv()],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="trajeto-resumo-mobilidade.csv";a.click();URL.revokeObjectURL(url)};return <section className="rounded-3xl border border-[#CFD9DD] bg-white p-4 text-[#0B1014] shadow-[0_12px_35px_rgba(11,16,20,.06)] sm:p-6" aria-labelledby="mobility-dashboard-title"><div className="flex items-start justify-between gap-3"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.14em] text-[#326575]">Meu dia a dia</p><h2 id="mobility-dashboard-title" className="mt-1 font-display text-2xl font-semibold tracking-[-0.045em]">Resumo de mobilidade.</h2><p className="mt-2 text-xs text-[#617179]">Gastos registrados em {month}. Só considera o que você informou no aparelho.</p></div><CalendarDays className="mt-1 size-5 text-[#326575]"/></div><div className="mt-5 grid gap-2 sm:grid-cols-3"><div className="rounded-2xl bg-[#F3F6F4] p-4"><Fuel className="size-4 text-[#326575]"/><p className="mt-3 text-[0.58rem] font-bold uppercase tracking-[0.12em] text-[#718089]">Combustível</p><p className="mt-1 text-xl font-black">{money(summary.fuelCost)}</p><p className="text-[0.6rem] text-[#718089]">{summary.fuelEntries} abastecimento(s)</p></div><div className="rounded-2xl bg-[#F3F6F4] p-4"><Receipt className="size-4 text-[#326575]"/><p className="mt-3 text-[0.58rem] font-bold uppercase tracking-[0.12em] text-[#718089]">Extras</p><p className="mt-1 text-xl font-black">{money(summary.extraCost)}</p><p className="text-[0.6rem] text-[#718089]">{summary.extraEntries} despesa(s)</p></div><div className="rounded-2xl bg-[#0B1014] p-4 text-white"><p className="text-[0.58rem] font-bold uppercase tracking-[0.12em] text-white/50">Total informado</p><p className="mt-2 text-2xl font-black">{money(summary.total)}</p><p className="text-[0.6rem] text-white/55">{summary.entries} registro(s) no mês</p></div></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={download} disabled={!summary.entries} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[#D8E0E3] px-4 text-xs font-extrabold disabled:opacity-40"><Download className="size-3.5"/>Exportar mês</button><a href={appUrl("/planejar")} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#C7FF3C] px-4 text-xs font-extrabold text-[#0B1014]">Planejar próxima viagem <ArrowRight className="size-3.5"/></a></div></section>}