import { trpc } from "@/lib/trpc";
import { ArrowDown, ArrowUp, BarChart3, Download, Loader2, Minus, Sparkles, Trophy } from "lucide-react";
import { useMemo, useState } from "react";
import { monthlyRankingCsv } from "@/lib/monthlyRankingCsv";

function monthOptions() { const now = new Date(); return Array.from({ length: 6 }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - index, 1); return { value: `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`, label: date.toLocaleDateString("pt-BR", { month: "long", year: "numeric" }) }; }); }

function positionIndicator(change: number | null) { if (change == null) return { label: "Entrada", Icon: Sparkles, className: "text-[#F8C76B]" }; if (change > 0) return { label: `Subiu ${change}`, Icon: ArrowUp, className: "text-[#C7FF3C]" }; if (change < 0) return { label: `Caiu ${Math.abs(change)}`, Icon: ArrowDown, className: "text-[#FF9D8D]" }; return { label: "Manteve", Icon: Minus, className: "text-[#B7C5CC]" }; }

export function MonthlyRouteAlertRanking() {
  const options = useMemo(monthOptions, []); const [month, setMonth] = useState(options[0]?.value ?? ""); const ranking = trpc.personal.monthlyRouteAlertRanking.useQuery({ month }); const routes = ranking.data?.routes ?? []; const max = Math.max(1, ...routes.map(route => route.alerts));
  const download = () => { const blob = new Blob([monthlyRankingCsv(month, routes)], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `trajeto-ranking-corredores-${month}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  return <section className="mt-4 rounded-3xl border border-[#F8C76B]/30 bg-[#241D10] p-5 text-white sm:p-6"><div className="flex gap-3"><Trophy className="mt-0.5 size-5 shrink-0 text-[#F8C76B]" /><div><p className="text-[0.62rem] font-bold uppercase tracking-[.14em] text-[#F8C76B]">Ranking mensal</p><h3 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Corredores com mais alertas registrados.</h3><p className="mt-2 text-sm text-[#D4C5A4]">Classificação baseada nas notificações das suas assinaturas. A variação compara a posição com o mês anterior; uma entrada não tinha alerta registrado no período anterior.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><label className="block w-full max-w-sm text-[.62rem] font-bold uppercase tracking-[.1em] text-[#D4C5A4]">Mês<select value={month} onChange={event => setMonth(event.target.value)} className="mt-1 block min-h-10 w-full rounded-lg border border-white/15 bg-[#0B1014] px-3 text-sm normal-case text-white">{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><button onClick={download} disabled={!routes.length} className="inline-flex min-h-10 items-center justify-center rounded-lg border border-[#F8C76B]/55 px-3 text-sm font-bold text-[#FFE5A9] disabled:opacity-50"><Download className="mr-2 size-4" />Exportar CSV</button></div>{ranking.isLoading ? <div className="mt-5 flex items-center text-sm text-[#D4C5A4]"><Loader2 className="mr-2 size-4 animate-spin" />Montando ranking…</div> : routes.length ? <ol className="mt-5 space-y-3">{routes.map((route, index) => { const indicator = positionIndicator(route.positionChange); const Icon = indicator.Icon; return <li key={route.corridorId} className="rounded-xl border border-white/10 bg-black/15 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold text-white"><span className="mr-2 text-[#F8C76B]">#{index + 1}</span>{route.corridorLabel}</p><p className="text-sm font-bold text-[#F8C76B]">{route.alerts}</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><i className="block h-full rounded-full bg-[#F8C76B]" style={{ width: `${route.alerts / max * 100}%` }} /></div><div className="mt-2 flex items-center justify-between gap-2 text-xs"><p className="text-[#D4C5A4]">{route.unread} não lido(s) · {route.latestAt ? `último em ${new Date(route.latestAt).toLocaleDateString("pt-BR")}` : "sem data disponível"}</p><span className={`inline-flex items-center font-bold ${indicator.className}`}><Icon className="mr-1 size-3.5" />{indicator.label}</span></div></li>; })}</ol> : <div className="mt-5 flex min-h-24 flex-col justify-center border-y border-dashed border-white/15 text-sm text-[#D4C5A4]"><BarChart3 className="mb-2 size-5 text-[#F8C76B]" />Sem notificações registradas neste mês para suas assinaturas.</div>}</section>;
}
