import { trpc } from "@/lib/trpc";
import { BellRing, Loader2, Route as RouteIcon } from "lucide-react";

export function WeeklyRouteAlertSummary() {
  const summary = trpc.personal.weeklyRouteAlertSummary.useQuery();
  const data = summary.data;
  const top = data?.routes.slice(0, 5) ?? [];
  return <section className="mt-8 rounded-3xl border border-[#3DE3FF]/25 bg-[#101C25] p-6 text-white sm:p-7"><div className="flex items-start justify-between gap-5"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.14em] text-[#3DE3FF]">Resumo semanal de alertas</p><h2 className="font-display mt-3 text-3xl font-semibold tracking-[-0.055em]">Rotas que mais pediram atenção.</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-[#A8BBC3]">Contagem das notificações registradas nos últimos sete dias para suas assinaturas. Uma ocorrência não prova congestionamento atual; abra a assinatura para consultar o estado mais recente.</p></div><BellRing className="size-6 text-[#C7FF3C]" /></div>{summary.isLoading ? <div className="mt-7 flex min-h-28 items-center justify-center text-sm text-[#A8BBC3]"><Loader2 className="mr-2 size-4 animate-spin" />Calculando a semana…</div> : top.length ? <div className="mt-7 grid gap-3 lg:grid-cols-5">{top.map((route, index) => <article key={route.corridorId} className="border border-white/10 bg-white/[0.04] p-4"><p className="text-[0.62rem] font-bold uppercase tracking-[0.12em] text-[#3DE3FF]">{String(index + 1).padStart(2, "0")} · {route.active ? "Assinada" : "Inativa"}</p><p className="mt-3 min-h-10 text-sm font-bold text-white">{route.corridorLabel}</p><p className="mt-4 font-display text-4xl font-semibold tracking-[-0.07em] text-[#C7FF3C]">{route.alerts}</p><p className="mt-1 text-xs text-[#A8BBC3]">alerta(s) na semana · {route.unread} não lido(s)</p><p className="mt-3 border-t border-white/10 pt-3 text-[0.68rem] text-[#829AA5]">{route.lastAlertAt ? `Último: ${new Date(route.lastAlertAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}` : "Sem alerta registrado"}</p></article>)}</div> : <div className="mt-7 flex min-h-28 flex-col justify-center border-y border-dashed border-white/15 text-sm text-[#A8BBC3]"><RouteIcon className="mb-3 size-5 text-[#3DE3FF]" /><p className="font-bold text-white">Nenhuma rota alertada nesta semana.</p><p className="mt-1">Suas assinaturas aparecerão aqui quando houver ocorrências acionáveis registradas.</p></div>}{summary.isError && <p role="alert" className="mt-4 text-sm text-[#FFC2B7]">Não foi possível montar o resumo semanal agora.</p>}</section>;
}
